/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
/**
 *
 * @author ASUS
 */
public class Frame1 extends javax.swing.JFrame { 
    int target;
    int attempts = 10;
    int score = 0;
    boolean gameaktif = false;
    private DefaultListModel<String> listModel;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        listModel = new DefaultListModel<>();
        kscore.setModel(listModel);
        resetGame();
    } 
    private void resetGame() {
        Random rand = new Random();
        target = rand.nextInt(100) + 1; 
        System.out.println("Target: " + target);
        attempts = 10; 
        score = 0;
        atebak.setText("");
        apetunjuk.setText("");
        ascore.setText("");
        ptebak.setText("TEBAK (10)");
        preset.setText("PLAY"); 
        gameaktif = false; 
        ptebak.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atebak = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apetunjuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ascore = new javax.swing.JTextField();
        ptebak = new javax.swing.JButton();
        preset = new javax.swing.JButton();
        pkeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tscore = new javax.swing.JScrollPane();
        kscore = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(102, 51, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("TEBAK ANGKA KU !");

        jLabel2.setText("TEBAK");

        jLabel3.setText("CLUE");

        apetunjuk.setEditable(false);

        jLabel4.setText("SCORE");

        ascore.setEditable(false);
        ascore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascoreActionPerformed(evt);
            }
        });

        ptebak.setText("TEBAK (10)");
        ptebak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptebakActionPerformed(evt);
            }
        });

        preset.setText("RESET");
        preset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presetActionPerformed(evt);
            }
        });

        pkeluar.setText("KELUAR");
        pkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(atebak)
                            .addComponent(apetunjuk)
                            .addComponent(ascore, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ptebak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preset)
                        .addGap(29, 29, 29)
                        .addComponent(pkeluar)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(atebak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apetunjuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ascore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preset)
                    .addComponent(ptebak)
                    .addComponent(pkeluar))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Permainan", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setText("SCORE");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        kscore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tscore.setViewportView(kscore);

        jPanel4.add(tscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 360, 160));

        jTabbedPane1.addTab("Score", jPanel4);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sae.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void presetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presetActionPerformed
        // TODO add your handling code here:
        if (!gameaktif) {
        gameaktif = true;
        preset.setText("RESET");
        atebak.setEditable(true); 
        JOptionPane.showMessageDialog(this, "Game dimulai! Silakan tebak angka.");
    } else {
        resetGame();
    }
    }//GEN-LAST:event_presetActionPerformed

    private void ptebakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptebakActionPerformed
        // TODO add your handling code here:
        if (!gameaktif) { 
            JOptionPane.showMessageDialog(this, "Tekan tombol PLAY terlebih dahulu!");
            return;
        }

        try { 
            int kamu = Integer.parseInt(atebak.getText());
            if (kamu < 1 || kamu > 100) { 
                JOptionPane.showMessageDialog(this, "Masukkan angka antara 1-100");
                return;
            }

            attempts--;
            ptebak.setText("TEBAK (" + attempts + ")");

            if (kamu < target) {
                apetunjuk.setText("Lebih besar");
            } else if (kamu > target) {
                apetunjuk.setText("Lebih kecil");
            } else { 
                apetunjuk.setText("Aku adalah angka " + kamu);

                String name = JOptionPane.showInputDialog("Masukkan nama Anda dengan benar:");
                if (name != null && !name.isEmpty()) {
                    score = 100 - (9 - attempts) * 10;
                    listModel.addElement("Nama: " +  name + " - " + "Selamat Kamu Mendapatkan Score: " + score); 
                    ascore.setText(String.valueOf(score));
                    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/ssstik.io_@mrgeckomanfrfr_1729042349223.gif"));
                    JOptionPane.showMessageDialog(this, "Selamat " + name + "! Skor Anda: " + score, "Informasi", JOptionPane.PLAIN_MESSAGE, icon);
                }

                ptebak.setEnabled(false);
                return;
                }

                if (attempts == 0) { 
                    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/ssstik.io_@mrgeckomanfrfr_1729042349223.gif"));
                    JOptionPane.showMessageDialog(this, "Anda Gagal! Angka yang benar adalah " + target, "Informasi", JOptionPane.PLAIN_MESSAGE, icon);
                    resetGame(); 
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid");
        }

    }//GEN-LAST:event_ptebakActionPerformed

    private void ascoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ascoreActionPerformed

    private void pkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pkeluarActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this,
            "Keluar Program",
            "Keluar",
            JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        } 
    }//GEN-LAST:event_pkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apetunjuk;
    private javax.swing.JTextField ascore;
    private javax.swing.JTextField atebak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> kscore;
    private javax.swing.JButton pkeluar;
    private javax.swing.JButton preset;
    private javax.swing.JButton ptebak;
    private javax.swing.JScrollPane tscore;
    // End of variables declaration//GEN-END:variables
}
